spring:
  application:
    name: Backend
  #Tejas@301005
  # Database Configuration
  datasource:
    username: root
    password: 8999617581@Sh
    url: jdbc:mysql://localhost:3306/pbl25
    name: PBL
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

        #logging.level.org.hibernate.SQL=DEBUG
        #logging.level.org.hibernate.transaction=TRACE

  # Spring Security
  security:
    user:
      name: user
      password: user

# Server specification
server:
  port: 8081

# Request Information and their status when they are called by another application
logging:
  level:
    org:
      springframework:
        web: DEBUG
        web.filter.CommonsRequestLoggingFilter: DEBUG