spring:
  application:
    name: Backend

  # Database Configuration
  datasource:
    username: root
    password: 8999617581@Sh
    url: jdbc:mysql://localhost:3306/pbl25
    name: PBL
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# Server specification
server:
  port: 8081

# Logging Configuration
logging:
  level:
    org:
      springframework:
        web: DEBUG
        web.filter.CommonsRequestLoggingFilter: DEBUG

# JWT Configuration
jwt:
  secret: "eA7S1nVl3pC8Hjk2mL9FQvX4T6YpJqW8rMbGzKdY5N0="